# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ILA_PWM.xci
# IP: The module: 'ILA_PWM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_PWM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_PWM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ILA_PWM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_PWM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ILA_PWM.xci
# IP: The module: 'ILA_PWM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_PWM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_PWM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/240689/VIO_ILA/IP/ILA_PWM/ILA_PWM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ILA_PWM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
