# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/240689/FIR/SOURCES/IP/FIR_50_MHz/FIR_50k/FIR_50k.xci
# IP: The module: 'FIR_50k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/240689/FIR/SOURCES/IP/FIR_50_MHz/FIR_50k/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/240689/FIR/SOURCES/IP/FIR_50_MHz/FIR_50k/FIR_50k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/240689/FIR/SOURCES/IP/FIR_50_MHz/FIR_50k/FIR_50k.xci
# IP: The module: 'FIR_50k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/240689/FIR/SOURCES/IP/FIR_50_MHz/FIR_50k/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/240689/FIR/SOURCES/IP/FIR_50_MHz/FIR_50k/FIR_50k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIR_50k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
