# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/240689/ARM_demo/SOURCES/rp_top.xdc

# Block Designs: C:/Users/240689/ARM_demo/BD/rp_zynq/rp_zynq.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rp_zynq || ORIG_REF_NAME==rp_zynq} -quiet] -quiet

# IP: c:/Users/240689/ARM_demo/BD/rp_zynq/ip/rp_zynq_processing_system7_0_0/rp_zynq_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rp_zynq_processing_system7_0_0 || ORIG_REF_NAME==rp_zynq_processing_system7_0_0} -quiet] -quiet

# IP: c:/Users/240689/ARM_demo/BD/rp_zynq/ip/rp_zynq_axi_gpio_0_0/rp_zynq_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rp_zynq_axi_gpio_0_0 || ORIG_REF_NAME==rp_zynq_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Users/240689/ARM_demo/BD/rp_zynq/ip/rp_zynq_ps7_0_axi_periph_0/rp_zynq_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rp_zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==rp_zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: c:/Users/240689/ARM_demo/BD/rp_zynq/ip/rp_zynq_rst_ps7_0_125M_0/rp_zynq_rst_ps7_0_125M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rp_zynq_rst_ps7_0_125M_0 || ORIG_REF_NAME==rp_zynq_rst_ps7_0_125M_0} -quiet] -quiet

# IP: c:/Users/240689/ARM_demo/BD/rp_zynq/ip/rp_zynq_auto_pc_0/rp_zynq_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rp_zynq_auto_pc_0 || ORIG_REF_NAME==rp_zynq_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/240689/ARM_demo/BD/rp_zynq/rp_zynq_ooc.xdc
